name: build and push image (Alpine version)

on:
  push:
    branches:
      - 'master'
    paths:
      - Dockerfile
      - .github/workflows/docker-build-alpine.yml
      - renew*.py

env:
  IMAGE_NAME: "habuild/noip-renewer"
  SELENIUM_VERSION: "4.5.0" # renovate: datasource=pypi depName=selenium versioning=pep440
  PIP_VERSION: "22.2.2" # renovate: datasource=pypi depName=pip versioning=pep440
  GOOGLETRANS_VERSION: "3.1.0a0"
  REQUESTS_VERSION: "2.28.1" # renovate: datasource=pypi depName=requests versioning=pep440

jobs:
  build_alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Get commit short hash
        id: short_sha
        run: echo "::set-output name=shortsha::$(git rev-parse --short HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.short_sha.outputs.shortsha }}-alpine
            ${{ env.IMAGE_NAME }}:alpine
            ${{ env.IMAGE_NAME }}:latest
          file: Dockerfile
          build-args: |
            SELENIUM_VERSION=${{ env.SELENIUM_VERSION }}
            PIP_VERSION=${{ env.PIP_VERSION }}
            GOOGLETRANS_VERSION=${{ env.GOOGLETRANS_VERSION }}
            REQUESTS_VERSION=${{ env.REQUESTS_VERSION }}

  delete_old_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 15
          keep_minimum_runs: 5
